# Generated by Django 4.2 on 2023-04-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
