# Generated by Django 4.2 on 2023-04-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_books_bookid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='bookid',
            new_name='book_id',
        ),
    ]
